# Cluster/service specific passwords (can be encrypted by ansible-vault)
secrets:
  testcluster1:
    valkeydb-mytest:
      default:
        password: testpass1
  #     dev:
  #       password: testpass2
  #     qa:
  #       password: testpass3
  # testcluster2:
  #   valkeydb:
  #     default:
  #       password: testpass1
  #     testdb1:
  #       password: testpass2
  # testcluster3:
  #   valkeydb:
  #     default:
  #       password: testpass1
  #   valkeydb-testsubcluster:
  #     default:
  #       password: testpass2
